Exception handling corrections
ooer-dev/botto-js pull request #1
Opened 2022-07-03 11:28 UTC by ArthaTi

Botto will no longer crash if something goes wrong in the API, for example it posts to the wrong channel or crosses 2000 characters.

2022-07-23 05:05 UTC, williammck requested changes

2022-07-23 05:05 UTC, williammck commented on src/discord/cache.js
> +    const json = JSON.parse(rawFile);
```suggestion
    const json = JSON.parse(rawFile)
```

bad semicolon, nobody likes you

2022-07-23 05:05 UTC, williammck commented on src/discord/cache.js
> +    const channels = json.channels
can we have it pull from `caches` if that's present? would make the current file compatible

2022-07-23 05:05 UTC, williammck commented on src/index.js
> +  try {
idk how I feel about wrapping this whole function in a try/catch. wonder if there's a nicer way to do this... i think you can do `bot.on('error', function (err) { ... })` and any uncaught exception from the EventEmitter will end up in there

side note, i'm looking at using https://www.sapphirejs.dev/ for commands and such, haven't investigated its error handling yet.

2022-07-23 05:05 UTC, williammck commented on src/index.js
> +      try {
ditto my above comment

2022-07-23 05:08 UTC, ArthaTi commented
oops i must have introduced some local changes that weren't supposed to be on this branch

2022-08-13 20:35 UTC, ArthaTi commented
I've completely lost interest in running botto and fixing this

2022-08-13 20:35 UTC, closed without merging